--- 
modules: 
  blog: true
  documents: false
  galleries: false
  store: false
  events: false
  product: false
  version: 1.0.0
  pages: true
  newsletters: false
  links: true
  members: true
keys: 
  sharethis: 998f13df-36bb-4d5b-96fc-c750d3a55a99
  google_maps: 
development_keys: 
  google_maps: ABQIAAAAcFCYQRnwVUthPL-ySCSjJBTJQa0g3IQ9GZqIMmInSLzwtGDKaBS8HXDFpTZcTkemWroqwX691T1xpg
website: 
  name: AMS Entertainment
  logo_position: top
  demo_message: 
  icon_domain: http://www.site-ninja.com
  domain: amsentertainment.com
  demo: false
  template: t3c7
features: 
  testimonials: true
  feature_box: true
  event_registration: true
site_settings: 
  event_title: 
  blog_title: Blog
  file_up_size: 20
  article_title: Post
  third_level_menu: left
  events_title: 
  links_title: Directory Listing
  link_title: Resource
  sendgrid_username: mailer@amsentertainment.com
  sengrid_password: 1234Mail