--- 
keys: 
  sharethis: 998f13df-36bb-4d5b-96fc-c750d3a55a99
  google_maps: 
modules: 
  blog: true
  documents: false
  events: false
  store: false
  galleries: false
  newsletters: false
  pages: true
  version: 1.0.0
  product: false
  members: true
  links: true
development_keys: 
  google_maps: ABQIAAAAcFCYQRnwVUthPL-ySCSjJBTJQa0g3IQ9GZqIMmInSLzwtGDKaBS8HXDFpTZcTkemWroqwX691T1xpg
features: 
  testimonials: true
  feature_box: true
  event_registration: true
website: 
  logo_position: top
  name: AMS Entertainment
  demo_message: 
  icon_domain: http://www.site-ninja.com
  domain: amsentertainment.com
  demo: false
  template: t3c7
site_settings: 
  event_title: 
  blog_title: Blog
  file_up_size: 20
  article_title: Post
  links_title: Directory Listing
  events_title: 
  third_level_menu: left
  link_title: Resource
